### ISSUE TITLE
ReadMe samples not working

### ISSUE THREAD

**Issue by Jack-Collins** [baloise/rocket-chat-rest-client#2]
```
RocketChatClient rc = new RocketChatClient("https://demo.rocket.chat/", "<user>", "<pw>");
```

I am using the username and password to authenticate but it is not allowing me any permissions and is giving an access_denied error for the other sample calls in this readme. Do I need further authentication?

**Comment by Jack-Collins** [comment]
I should add - the account I am logging into is not an admin account but a regular user account - would that mean I won't have the permissions to even to a simple getPublicRooms() call via the API?

**Comment by anvay452** [comment]
not able to run

java.io.IOException: com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
    at com.github.baloise.rocketchatrestclient.RocketChatClient.getVersions(RocketChatClient.java:130)
    at com.github.baloise.rocketchatrestclient.RocketChatClient.getRocketChatVersion(RocketChatClient.java:119)
    at com.stoneriver.portal.agency.ui.controller.NavbarComposer.userProfile(NavbarComposer.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.zkoss.zk.ui.select.Selectors$ComposerEventListener.onEvent(Selectors.java:690)
    at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:3030)
    at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3001)
    at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2942)
    at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
    at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1826)
    at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1611)
    at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1321)
    at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:611)
    at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:485)
    at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:494)

**Comment by anvay452** [comment]
worked , now can access data 👍 
change 
`RocketChatClient rc = new RocketChatClient("https://demo.rocket.chat/api/", "<user>", "<pw>");`
