### ISSUE TITLE
Problems with mvn clean install

### ISSUE THREAD

**Issue by col-panic** [baloise/rocket-chat-rest-client#33]
The following problems exist during `mvn clean install`
 

1.  The download url in Dockerfile is wrong, it has to be changed to 
```
 && curl -SLf "https://releases.rocket.chat/${RC_VERSION}/download" -o rocket.chat.tgz \
 && curl -SLf "https://releases.rocket.chat/${RC_VERSION}/asc" -o rocket.chat.tgz.asc \
```

2. the build fails with - i'm not sure whether this is an OS X only problem
```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /app/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: 1: nodejs: not found
npm ERR! Linux 4.9.184-linuxkit
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.0 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/bundle/programs/server/npm-debug.log
```

**Comment by MarkusTiede** [comment]
Hi @col-panic - thanks for noticing and the detailed description! I'll try to reproduce within a "clean environment": http://gitpod.io/#https://github.com/baloise/rocket-chat-rest-client

**Comment by col-panic** [comment]
Any news on this? thanks

**Comment by MarkusTiede** [comment]
Hi @col-panic - unfortunately I couldn't setup the environment properly on gitpod.io: I've now tried a local 'mvn clean verify' on my MacOS machine: same error. 

I think we'll have to wait for the CODEOWNER to return (from vacation). 

However I've pushed the modifications I did so far to https://github.com/baloise/rocket-chat-rest-client/tree/GH-33

**Comment by MarkusTiede** [comment]
I @culmat could you please have a short look into this?

**Comment by col-panic** [comment]
ping :)

**Comment by kullmanp** [comment]
I can reproduce this also. And I don't think it has to do anything with the mac (although I am also using a mac). To solve the issue I tried the following things (but without success until now): 
- installing python on the image: This is not enough. One would need make, g++ and possibly more in order to install fibers. 
- using a more recent base image: instead of rocketchat/base:4 I switched to base:8. With this the image can be created. But the integration test still doesn't work because it cannot connect to the mongo db. It stops with the following error: 
```
/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Error: Unable to find Mongodb Oplog. You must run the server with oplog enabled. Try the following:

				1. Start your mongodb in a replicaset mode: mongod --smallfiles --oplogSize 128 --replSet rs0

				2. Start the replicaset via mongodb shell: mongo mongo/meteor --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"

				3. Start your instance with OPLOG configuration: export MONGO_OPLOG_URL=mongodb://localhost:27017/local MONGO_URL=mongodb://localhost:27017/meteor node main.js
				
    at BaseDb.handleListener (app/models/server/models/_BaseDb.js:51:11)
    at emitTwo (events.js:126:13)
    at BaseDb.emit (events.js:214:7)
    at _addListener (events.js:249:14)
    at BaseDb.addListener (events.js:297:10)
    at emitter.js (app/authorization/server/publications/permissions/emitter.js:4:13)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/authorization/server/publications/permissions/index.js:1:178)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/authorization/server/index.js:1:1746)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
````
- Adding the oplog to the mongo startup didn't help on the first try - some more settings have to be set, I think. If I can find some time I will continue to investigate.

**Comment by col-panic** [comment]
I try to get the build and test back running, but am currently blocked by https://github.com/fabric8io/docker-maven-plugin/issues/244 to which I do not seem to find a solution ...
